apiVersion: v1
kind: Pod
metadata:
  name: cache
spec:
  containers:
    - image: redis
      name: cache
---
apiVersion: v1
kind: Service
metadata:
  name: cache
spec:
  selector:
    name: cache
  ports:
    - protocol: TCP
      port: 6379
