apiVersion: v1
kind: Pod
metadata:
  name: cache
  labels:
    type: cache
spec:
  containers:
    - image: redis
      name: cache
---
apiVersion: v1
kind: Service
metadata:
  name: cache
spec:
  selector:
    type: cache
  ports:
    - protocol: TCP
      port: 6379
