apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-volume
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: db
  labels:
    tier: database
spec:
  containers:
    - image: mongo
      name: mongo
      volumeMounts:
        - mountPath: "/data/db"
          name: vol
  volumes:
    - name: vol
      persistentVolumeClaim:
        claimName: db-volume
---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    tier: database
  ports:
    - protocol: TCP
      port: 27017